language: python
services:
- postgresql
env:
- DATABASE_URL=postgres://postgres:postgres@localhost/meetup-finder
before_install:
- export DJANGO_SETTINGS_MODULE=meet_up_finder.settings
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c "CREATE USER nickc WITH PASSWORD 'meetup-finder';" -U postgres
- psql -c 'CREATE DATABASE "meetup-finder" OWNER nickc;' -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE "meetup-finder" to nickc;' -U postgres
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py collectstatic --noinput
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: AQVQPsWCOzFNaqWQ0axpytSn+NbEFD8eJ/2tBs/NNoM2OUb3JxlAWqG6FcLdoMg7w7VGlij7xuZZm3RhzB0aCqMjNDN5VuGN20P+D0RexmQzbhnDOlyZD6PiRdxvDqx1JXVKs6kF4GOlaesu9UbjsVwhS+Lxd2MUd5NybmQwFNNHG105kKQfW11A1diMAzOGceKIOxYuFwDcgTdsNhQzouy4FRb/O1xMmHe/o4V+duQhEFhEt5MKNlhUzBFrV2jVdyh/MW9a3+H++YqUvu6/A8rAAuI5uI6/17Q45FK4X8WwQdL4QRUBLNyAlj/eGg2c63IOk6A+qLXiQPB6CAzNJiz+OfJ9UjDh/czK3jlmotLSa8Zp5/WFrNgfQELNKGEHBowMRnLM5GYEy5KXd6KUJOs2LYDgvkVz/zTISuOuEhiljcMAJO5PTKIZ90FAhP2+OgnVJ0k85hPwJsr01JRTYJIkKY5vB9Iy0VlqxIs63Ng+CTv00EWNDH3YsGCzsl7H3uGHLz9j3TOH+v5ZNQ1DPvgaCjsRCt3UfQDfFGB5L4xboIpMGaRDF6JeOQokX/WG8FntYleVzfw/fXKmlnNwcweywO/w6mSh3rNL4vsYUcckn8TcZNBSNkSpkk/6WJ8bQ8eyuBmXCUfvXQV6fFt/ZOz99Rxu5bD66yYf53GpngI=
  app: project-1-25
  run: rake db:migrate
  on:
    repo: uva-cs3240-f20/project-1-25
    branch: master
  skip_cleanup: true
