language: python
services:
- postgresql
env:
- DATABASE_URL=postgres://postgres:postgres@localhost/meetup-finder
before_install:
- export DJANGO_SETTINGS_MODULE=meet_up_finder.settings
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c "CREATE USER nickc WITH PASSWORD 'meetup-finder';" -U postgres
- psql -c 'CREATE DATABASE "meetup-finder" OWNER nickc;' -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE "meetup-finder" to nickc;' -U postgres
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py collectstatic --noinput
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Gh87cfhda+E2i+6iombx78PB7ES7IH7GQjMZPo9WQt9zTgaRMaqxP3My1ddBoIifJk+nDrfRttTlOwamaaeD855Utf9o8bcknYgASQnU8hrfYElYoQnLNUq5OH4g22i7tiExHdymo4n6a3yWDotBfIklD3cNGWqbZauLEGX0zGD88LWwivRb1IJRGir5WsgIlP5zBLVCmI2rXGpHEPGDvm8o++vYMnPt3KIh99rSVYGgUhl9DinYZIgl2ragwPG4t/Zb7vpztFncLTWrl40kHoWlFUofLc5NFYqL45Y0TRAYkrP2MyN9qvOlWktdq7mYGvVecCtvZPHbGDd1ZUuNpSdCGwf64AxKDe9c7XXDdnUQgjgrBPlJjD98SwPYUUu95+ncChnBk3nXf4YKSr6YBBPbnNhX0BAx7U6GBOBPqhlfygXR55ZgwTQT/jgL1sCShc01E8fcLQf4KXWDcyi605snsgYFCrHnuv0jZi4kH94eNd/dr45lzRo5/HB+YV1kdVCnvK2NBUtR1VmYw5Hg56qSbx7x75qm0gIeIGVcaY+3iKv3IvMJ2L7k9DZccJ1wlF0TqkjvZyTaRK09DowAtMWuc3UhIkdHwIFqIg8IwvhkK+uNpoMLU/qlz7237LfJZ1xyd0aGIamTFbQk5bnQ9rpJI5Fu6/5ayszFW5A4OgI=
    # d8WdjYPO0ttnZXsj5bcItd5E+jVe+Htt1EsWbJySFjCxIRzklbaxUKElItGXeWLfBgl+oQwb8qsUpWp5Dmdom9PfySXmLpnF4Y4Aoi+/rhZ0DXh/wzqCF8ikgQmc8EE30ZciMZwzwF1jfk8d5dJm8dbAaWO70+tulWyftR6TkPKwByknrwLtN/QnZ4E7eahQmHZZiORmnbSlg9CtetHVHqkiAfSu1AaqRYrInT+dww0v70ZyJe2donK7Dcp07CHOn5+FFTt8hg9Ae6PHDrvRH5Qw787pch18Q+QFtT5m6IePHp91jEULojjMn8mew77B9UjsiAN51sSzI0pt5Z6j9p39bvx/0JFE4GF8aSMoYWQC8MeUHJQTgzhgHnNUtizoDg2CbEneRFCWwTuJwfxk4zKnidYHBXteMRDLqrSzykMJfx/yk761beCEkS0CRYauyml0dft6wRKPasqti7vzCd+tjEta2WOl7KDuWO5J4H+LKMk9s71Kzvz5eqOTnrJe4FOAINA/4RbEP7KSgW7PB+4HOUP34YJ7RTl0NYpde77ZciZdpCp4Cl3eHxmX4wmLD6koBew10vhsTNL7N6gpASBIxU5XSllXodUzkLs5zHEMqx3Atfh1LVo0G7Cy1MZE4EWKGXSVZMRA2djTOOXk9BVgLySzKMbNBmvu6eXNl9A=
  app: project-1-25
  run: rake db:migrate
  on:
    repo: uva-cs3240-f20/project-1-25
    branch: master
  skip_cleanup: true
