language: python
services:
- postgresql
env:
- DATABASE_URL=postgres://postgres:postgres@localhost/meetup-finder
before_install:
- export DJANGO_SETTINGS_MODULE=meet_up_finder.settings
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c "CREATE USER nickc WITH PASSWORD 'meetup-finder';" -U postgres
- psql -c 'CREATE DATABASE "meetup-finder" OWNER nickc;' -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE "meetup-finder" to nickc;' -U postgres
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py collectstatic --noinput
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: bfrEqXO6IFZu7vocsWqRxX5wV3ZOx92Pfjgmpea7r81sSj8SoEnyi+5qAGNCmzLfrmdCcNWRZDYA5VwG6nWRV02m2eQm30rj0XgMfcg1mut9yCNXtHQNG82WgsM6XFGG6xHvWP+HdWy6Jgfguync9KQm6vmjNMohITszBYcI4n/2JiaUO44pUioDop6NVyTo+bLsjhWUAeM2qp7q37DpvL1j1SownmBDx3b6AI8dA71empNClN+59CWvzteNV8AYPGFG7J2I2uIPKnIZseJitdDD8/cnZpTXGLPS5LJ88O0sBHBtB3hlmx9OS4GcKCJMSkp/fyQURSgf1VtYOq9958JB2WYR9Ju/ZWy0b/+fC86Na6mlMWmjlpKzTrbgsKJvsfWIG+0Twc6If0X6JJB9mkPmBPhaifFx+ITagjLtQINEX3nEXbFhu6u6hj7Uh3jVffT9aHurMbGzCSS5fJmYXTBCnEFN4uach/zN117k1jFdcq+Z73i01/3WPLOHHJP8J1sqXXe36xlKx8l1bkBl6o1YawOvD7/j+gsnhhabEh0IZe7PIqRTvN9ifcHx4J4Ra/J8ueDXsWUpg9MjDnCwUKXQtgN3GMAhN9xrAymi5PLb7CUcAFeZnUMg+OlAZDFXqBDSVgeh6aZ2wEZLyyu6Kb/7Z8wugeJgdmo0wXDOdag=
  app: meetup-finder-1-25
  run: rake db:migrate
  on:
    repo: uva-cs3240-f20/project-1-25
    branch: master
  skip_cleanup: true
