language: python
services:
- postgresql
env:
- DATABASE_URL=postgres://postgres:postgres@localhost/meetup-finder
before_install:
- export DJANGO_SETTINGS_MODULE=meet_up_finder.settings
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c "CREATE USER nickc WITH PASSWORD 'meetup-finder';" -U postgres
- psql -c 'CREATE DATABASE "meetup-finder" OWNER nickc;' -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE "meetup-finder" to nickc;' -U postgres
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py collectstatic --noinput
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: NBGc22Nj4HpxZBuZRLDwcmjo3/tfvZHkfH4FXCDRVHmLZGv3GmGm/RNMWzYh6RhnqfpvT5XbXFSkLJ2BfRl2dB9l7X6miINKNxRR7XcxQ3cPDo20VoBh/GJXY2zui0RJQhKbM33hYNKDnc4Js6Pu/wblluVkA1NFsmsvyECAYZq42OtfPwAhvczaHYr7A/+FXMqKqxhN6zn+d5JEAGbSD0b6BMSizVVMNcQXGHq2xDKCcZSA8U/CctRTHMdxlV/V+BrpYcEdfzyf2v1m/ZWNw8oalqA+xxi6YDXc3XW9FgskmjW7fw9pBFyu5O4B8ZeZGM1U2angrs7ws+AFk/WlrzOLnpADsJCnC6B4bEas5a48Qw/cXoPyyhzDMH1AabZ08JoM74KIRdW/7N1zat8TzIGoZSW0C6r3CHmtxOFZDUGxRQczaiCOz/qrZ0w0R/p8tgXz8sgEhkFDg86bO48OJKTGN56h7duQUIOlsGhJcj/K9ITiPC35NT1X/KA3G6BANbC8Ihkm3Bc/lGGxx5rfC8INjpHBhQb3Md2ASwmILAZ4O/suCsr7s/upC/baDLMHL9IZuCGnatvLlKmImD4VKbG8hLNTgpDJotNWcbKHzsqo3IiavXPjd0Fk004XoVQh056TWywQZjpwzYab8PjAbTSjmQgUBEfeLBcdALBJ09o=
  app: meetup-finder-1-25
  run: rake db:migrate
  on:
    repo: uva-cs3240-f20/project-1-25
    branch: master
  skip_cleanup: true
