language: python
services:
- postgresql
env:
- DATABASE_URL=postgres://postgres:postgres@localhost/meetup-finder
before_install:
- export DJANGO_SETTINGS_MODULE=meet_up_finder.settings
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c "CREATE USER nickc WITH PASSWORD 'meetup-finder';" -U postgres
- psql -c 'CREATE DATABASE "meetup-finder" OWNER nickc;' -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE "meetup-finder" to nickc;' -U postgres
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py collectstatic --noinput
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: nG7OSLG0CNve8+NiJl9Nr5IqiG1e0do+hoQfPsQQfKxDc2x9du5GjAooJLwS7FgXi/QDkYU8PinFdLqIpd0ya/X1KmnIrjbEVZFbivRgyoXZzhCHHUjJBTnonc0L8sJoHx58ntlrNnE6V7LsI4Ya69U+xXMNzdUPNHlqd8B4ZQQ7kr6Aqv7bCYstKgs+GMJMtLxjow10ab3ulV6C5Fazb31srRCRsjtGxpArAogNibRHs2dQN+i+KYuCTxQ/um4AeYh1Wi9KKFwCKMTRNBxBAa0iUh9EyikT9Uz9uyKTEpG7bYU4s89vo3ckHgd7wpwY/CHV9CNdH6tlXS5xPn/LA+wTKZxUm/FpnZjhkcqTJ00olZgVO8mVBKcz8CoOlwdRZAY4+EbABf6+KPpsEOH5HjxRukF3WvBPuvkBwDAULsVpEDfDgRzVz9C/MzTHSlnwvpYg36Mox3Wgi1+2u5SDkyAMRXNt1qzpeUyZVGoOd4RCs+wVcTFlx7pWnktWoNeovtuJ5ybcPXK+eVHl5fAWsZYY0HywtpkL6YqDan+JX8PiF1fadEdBNTA4MUvpNtBCm+N15CN/z/DLcs0W8QO1kfE8ThxyjDagu67i1nvVy0M0uH6T3vPV7KSulA/uDiMxqamI8PqPnnZVCh70qulpNOAq6cLIKugSCuVJumaTkkk=
  app: meetup-finder-1-25
  run: rake db:migrate
  on:
    repo: uva-cs3240-f20/project-1-25
    branch: master
  skip_cleanup: true
